version: "3.8"
services:
  mongo:
    image: mongo
    container_name: meu-mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: senha123
    volumes:
      - ./mongo-data:/data/db
